spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.37.213:3306/online_order?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 247015
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    check-template-location: true
    servlet:
      content-type: text/html
    mode: HTML
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
server:
  port: 80
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dfyang.onlineorder.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql