spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///online_order?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 151310
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    check-template-location: true
    servlet:
      content-type: text/html
    mode: HTML
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 80
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dfyang.onlineorder.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true